### ISSUE TITLE
Steps to reproduce not working anymore

### ISSUE THREAD

**Issue by Selebrator** [smasher164/staticjni#3]
Hi, thanks for your blog post. Unfortunately The provided code and instructions don't work anymore. Here is a transcript of what happened.
I did not yet look into fix.

```
$ javac -cp . HelloWorld.java NativeFeature.java
NativeFeature.java:8: warning: [removal] AutomaticFeature in com.oracle.svm.core.annotate has been deprecated and marked for removal
@AutomaticFeature
 ^
1 warning
$ jar cfm HelloWorld.jar manifest.txt HelloWorld.class NativeFeature.class
$ cc -c -I "$JAVA_HOME/include" -I "$JAVA_HOME/include/linux" -o native.o Native.c
$ ar rcs libNative.a native.o
$ native-image -jar HelloWorld.jar -H:CLibraryPath=.
========================================================================================================================
GraalVM Native Image: Generating 'HelloWorld' (executable)...
========================================================================================================================
Warning: Feature class NativeFeature is annotated with the deprecated annotation @AutomaticFeature. Support for this annotation will be removed in a future version of GraalVM. Applications should register a feature using the option --features=NativeFeature
[1/8] Initializing...                                                                                    (2.9s @ 0.14GB)
 Java version: 17.0.8+7, vendor version: GraalVM CE 17.0.8+7.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: gcc (pc, x86_64, 13.2.1)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 1 user-specific feature(s)
 - NativeFeature

------------------------------------------------------------------------------------------------------------------------
                        0.2s (6.6% of total time) in 10 GCs | Peak RSS: 0.49GB | CPU load: 3.30
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/lukas/tmp/staticjni/svm_err_b_20231003T005346.748_pid944571.md (build_info)
========================================================================================================================
Failed generating 'HelloWorld' after 3.0s.

The build process encountered an unexpected error:

> java.lang.IllegalAccessError: class NativeFeature (in unnamed module @0x70abf9b0) cannot access class com.oracle.svm.core.jdk.NativeLibrarySupport (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.jdk to unnamed module @0x70abf9b0

Please inspect the generated error report at:
/home/lukas/tmp/staticjni/svm_err_b_20231003T005346.748_pid944571.md

If you are unable to resolve this problem, please file an issue with the error report at:
https://graalvm.org/support
```

# GraalVM Native Image Error Report

## Build Output

```
========================================================================================================================
GraalVM Native Image: Generating 'HelloWorld' (executable)...
========================================================================================================================
[1/8] Initializing...
                      
[1/8] Initializing...                                                                                    (2.9s @ 0.14GB)
 Java version: 17.0.8+7, vendor version: GraalVM CE 17.0.8+7.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: gcc (pc, x86_64, 13.2.1)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 1 user-specific feature(s)
 - NativeFeature

```

## Stack Trace

```java
java.lang.IllegalAccessError: class NativeFeature (in unnamed module @0x70abf9b0) cannot access class com.oracle.svm.core.jdk.NativeLibrarySupport (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core.jdk to unnamed module @0x70abf9b0
	at NativeFeature.beforeAnalysis(NativeFeature.java:14)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:757)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:86)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:757)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

## GraalVM Setup

| Name | Value |
| ---- | ----- |
| Java version | `17.0.8+7` |
| Vendor version | `GraalVM CE 17.0.8+7.1` |
| Runtime version | `17.0.8+7-jvmci-23.0-b15` |
| C compiler | `gcc (pc, x86_64, 13.2.1)` |
<details>
<summary>GraalVM <code>release</code> file</summary>

```
IMPLEMENTOR="GraalVM Community"
JAVA_RUNTIME_VERSION="17.0.8+7-jvmci-23.0-b15"
JAVA_VERSION="17.0.8"
JAVA_VERSION_DATE="2023-07-18"
LIBC="gnu"
MODULES="java.base java.compiler java.instrument java.logging java.management jdk.internal.vm.ci jdk.jfr jdk.unsupported org.graalvm.sdk java.datatransfer java.xml java.prefs java.desktop java.transaction.xa java.sql jdk.management org.graalvm.truffle jdk.internal.vm.compiler com.oracle.graal.graal_enterprise com.oracle.svm.extraimage_enterprise com.oracle.svm.svm_enterprise com.oracle.svm_enterprise.ml_dataset java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.incubator.foreign jdk.incubator.vector jdk.internal.le jdk.internal.opt jdk.internal.vm.compiler.management jdk.internal.vm.compiler.truffle.jfr jdk.jartool jdk.javadoc jdk.jcmd jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jlink jdk.jpackage jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.random jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported.desktop jdk.xml.dom jdk.zipfs org.graalvm.extraimage.builder org.graalvm.js.scriptengine org.graalvm.locator"
OS_ARCH="x86_64"
OS_NAME="Linux"
SOURCE=".:git:8f4e37e03307+ labsjdk-builder:12420ad1e23067e0d670c982075d354daedbe55e compiler:0d67c739da8f4ee40ed9796185205ed54935c06b graal-js:b8af554c627475fb02bf2d7820239d5e9b488bcb java-benchmarks:0d67c739da8f4ee40ed9796185205ed54935c06b regex:0d67c739da8f4ee40ed9796185205ed54935c06b sdk:0d67c739da8f4ee40ed9796185205ed54935c06b substratevm:0d67c739da8f4ee40ed9796185205ed54935c06b tools:0d67c739da8f4ee40ed9796185205ed54935c06b truffle:0d67c739da8f4ee40ed9796185205ed54935c06b vm:0d67c739da8f4ee40ed9796185205ed54935c06b"
GRAALVM_VERSION="23.0.1"
COMMIT_INFO={"compiler": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1689926320, "commit.rev": "0d67c739da8f4ee40ed9796185205ed54935c06b"}, "graal-js": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1689063743, "commit.rev": "b8af554c627475fb02bf2d7820239d5e9b488bcb"}, "java-benchmarks": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1689926320, "commit.rev": "0d67c739da8f4ee40ed9796185205ed54935c06b"}, "regex": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1689926320, "commit.rev": "0d67c739da8f4ee40ed9796185205ed54935c06b"}, "sdk": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1689926320, "commit.rev": "0d67c739da8f4ee40ed9796185205ed54935c06b"}, "substratevm": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1689926320, "commit.rev": "0d67c739da8f4ee40ed9796185205ed54935c06b"}, "tools": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1689926320, "commit.rev": "0d67c739da8f4ee40ed9796185205ed54935c06b"}, "truffle": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1689926320, "commit.rev": "0d67c739da8f4ee40ed9796185205ed54935c06b"}, "vm": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1689926320, "commit.rev": "0d67c739da8f4ee40ed9796185205ed54935c06b"}}
component_catalog="https://www.graalvm.org/component-catalog/v2/graal-updater-component-catalog-java17.properties|{ee=GraalVM Enterprise Edition}rest://gds.oracle.com/api/20220101/"
GDS_PRODUCT_ID="D53FAE8052773FFAE0530F15000AA6C6"
```

</details>

## Builder Setup

<details>
<summary>Class path</summary>

```
/home/lukas/tmp/staticjni/HelloWorld.jar
```

</details>

<details>
<summary>Module path</summary>

```
/usr/lib/jvm/java-17-graalvm/lib/svm/library-support.jar
/usr/lib/jvm/java-17-graalvm/lib/truffle/truffle-api.jar
/usr/lib/jvm/java-17-graalvm/lib/svm/builder/objectfile.jar
/usr/lib/jvm/java-17-graalvm/lib/svm/builder/native-image-base.jar
/usr/lib/jvm/java-17-graalvm/lib/svm/builder/pointsto.jar
/usr/lib/jvm/java-17-graalvm/lib/svm/builder/svm.jar
```

</details>

<details>
<summary>Builder arguments</summary>

```
-H:CLibraryPath=/usr/lib/jvm/java-17-graalvm/lib/svm/clibraries/linux-amd64
-H:Path=/home/lukas/tmp/staticjni
-H:Name@manifest from file:///home/lukas/tmp/staticjni/HelloWorld.jar=HelloWorld
-H:Class@manifest from file:///home/lukas/tmp/staticjni/HelloWorld.jar=HelloWorld
-H:CLibraryPath=/home/lukas/tmp/staticjni
-H:Features@jar:file:///usr/lib/jvm/java-17-graalvm/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties=com.oracle.svm.thirdparty.gson.GsonFeature
-H:Features@jar:file:///usr/lib/jvm/java-17-graalvm/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties=com.oracle.svm.polyglot.groovy.GroovyIndyInterfaceFeature,com.oracle.svm.polyglot.scala.ScalaFeature
-H:+BuildOutputColorful
-H:+BuildOutputProgress
-H:+BuildOutputLinks
```

</details>

<details>
<summary>Builder properties</summary>

```
-Dcom.oracle.graalvm.isaot=true
-Dgraalvm.ForcePolyglotInvalid=true
-Dgraalvm.locatorDisabled=true
-Djava.awt.headless=true
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader
-Djdk.internal.lambda.disableEagerInitialization=true
-Djdk.internal.lambda.eagerlyInitialize=false
-Djdk.module.main=org.graalvm.nativeimage.builder
-Dorg.graalvm.vendor=GraalVM Community
-Dorg.graalvm.vendorurl=https://www.graalvm.org/
-Dorg.graalvm.vendorversion=GraalVM CE 17.0.8+7.1
-Dorg.graalvm.version=23.0.1
-Dsubstratevm.HostLibC=glibc
-Dsubstratevm.IgnoreGraalVersionCheck=true
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime
-Dtruffle.TrustAllTruffleRuntimeProviders=true
```

</details>

<details>
<summary>Features enabled</summary>

```
NativeFeature, []
com.oracle.svm.core.ContainersFeature, []
com.oracle.svm.core.IsolateArgumentParserFeature, []
com.oracle.svm.core.IsolateListenerFeature, [com.oracle.svm.core.IsolateListenerSupportFeature]
com.oracle.svm.core.IsolateListenerSupportFeature, []
com.oracle.svm.core.RuntimeAssertionsSupportFeature, []
com.oracle.svm.core.StaticFieldsFeature, []
com.oracle.svm.core.StaticFieldsSupportFeature, []
com.oracle.svm.core.SubstrateExitHandlerFeature, []
com.oracle.svm.core.SubstrateSegfaultHandlerFeature, [com.oracle.svm.core.IsolateListenerSupportFeature]
com.oracle.svm.core.UniqueShortNameProviderDefaultImplFeature, []
com.oracle.svm.core.UnsafeMemoryUtilFeature, []
com.oracle.svm.core.allocationprofile.AllocationProfilingFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature]
com.oracle.svm.core.amd64.AMD64FrameAccessFeature, []
com.oracle.svm.core.c.CTypeConversionSupportImplFeature, []
com.oracle.svm.core.c.ProjectHeaderFileHeaderResolversRegistryFeature, []
com.oracle.svm.core.c.function.IsolateSupportImplFeature, []
com.oracle.svm.core.code.CodeInfoFeature, [com.oracle.svm.core.util.CounterFeature]
com.oracle.svm.core.code.CodeInfoMemoryWalkerFeature, []
com.oracle.svm.core.code.InstalledCodeObserverSupportFeature, []
com.oracle.svm.core.cpufeature.RuntimeCPUFeatureCheckFeature, []
com.oracle.svm.core.cpufeature.RuntimeCPUFeatureCheckImplFeature, []
com.oracle.svm.core.genscavenge.AlignedHeapChunkMemoryWalkerAccessImplFeature, []
com.oracle.svm.core.genscavenge.JfrGCEventFeature, []
com.oracle.svm.core.genscavenge.PinnedObjectImplPinnedObjectSupportImplFeature, []
com.oracle.svm.core.genscavenge.UnalignedHeapChunkMemoryWalkerAccessImplFeature, []
com.oracle.svm.core.genscavenge.graal.BarrierSnippetCountersFeature, [com.oracle.svm.core.util.CounterFeature]
com.oracle.svm.core.genscavenge.graal.GenScavengeGCFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature com.oracle.svm.core.jdk.management.ManagementFeature com.oracle.svm.core.jvmstat.PerfDataFeature com.oracle.svm.core.heap.AllocationFeature]
com.oracle.svm.core.graal.amd64.AMD64NativePatchConsumerFactoryFeature, []
com.oracle.svm.core.graal.amd64.SubstrateAMD64Feature, []
com.oracle.svm.core.graal.amd64.SubstrateAMD64GraphBuilderPlugins, []
com.oracle.svm.core.graal.jdk.JDKIntrinsicsFeature, []
com.oracle.svm.core.graal.snippets.CFunctionSnippetsFeature, []
com.oracle.svm.core.graal.snippets.DeoptSnippetsFeature, []
com.oracle.svm.core.graal.snippets.ExceptionFeature, []
com.oracle.svm.core.graal.snippets.SafepointFeature, []
com.oracle.svm.core.graal.snippets.StackOverflowCheckFeature, []
com.oracle.svm.core.graal.snippets.amd64.AMD64SnippetsFeature, []
com.oracle.svm.core.graal.stackvalue.StackValueFeature, []
com.oracle.svm.core.handles.ObjectHandlesSupportImplFeature, []
com.oracle.svm.core.heap.AllocationFeature, []
com.oracle.svm.core.heap.GCCauseFeature, []
com.oracle.svm.core.heap.HostedHeapSizeVerifierFeature, []
com.oracle.svm.core.heap.ReferenceAccessImplFeature, []
com.oracle.svm.core.heap.ReferenceHandlerThreadFeature, []
com.oracle.svm.core.heap.VMOperationInfosFeature, []
com.oracle.svm.core.heap.VMOperationNamesFeatures, []
com.oracle.svm.core.hub.ClassForNameSupportFeature, []
com.oracle.svm.core.hub.DynamicHubSupportFeature, []
com.oracle.svm.core.identityhashcode.SubstrateIdentityHashCodeFeature, []
com.oracle.svm.core.jdk.AtomicFieldUpdaterFeature, []
com.oracle.svm.core.jdk.ClassLoaderSupportFeature, []
com.oracle.svm.core.jdk.CompletableFutureFeature, []
com.oracle.svm.core.jdk.FileSystemProviderFeature, []
com.oracle.svm.core.jdk.ForkJoinPoolFeature, []
com.oracle.svm.core.jdk.InnocuousForkJoinWorkerThreadFeature, []
com.oracle.svm.core.jdk.JDKVersionSpecificResourceBuilderJDK11OrLaterFeature, []
com.oracle.svm.core.jdk.JRTDisableFeature, []
com.oracle.svm.core.jdk.JavaNetFeature, []
com.oracle.svm.core.jdk.JavaNetHttpFeature, []
com.oracle.svm.core.jdk.NativeLibrarySupportFeature, []
com.oracle.svm.core.jdk.PlatformNativeLibrarySupportFeature, []
com.oracle.svm.core.jdk.RecordSupportJDK11OrEarlierFeature, []
com.oracle.svm.core.jdk.ResourcesFeature, []
com.oracle.svm.core.jdk.RuntimeFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature]
com.oracle.svm.core.jdk.RuntimeSupportFeature, []
com.oracle.svm.core.jdk.SealedClassSupportJDK11OrEarlierFeature, []
com.oracle.svm.core.jdk.ServiceCatalogSupportFeature, []
com.oracle.svm.core.jdk.TimeZoneFeature, []
com.oracle.svm.core.jdk.TrustStoreManagerFeature, []
com.oracle.svm.core.jdk.URLProtocolsSupportFeature, []
com.oracle.svm.core.jdk.VarHandleFeature, []
com.oracle.svm.core.jdk.localization.LocalizationFeature, []
com.oracle.svm.core.jdk.management.ManagementFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature com.oracle.svm.core.thread.ThreadListenerSupportFeature]
com.oracle.svm.core.jdk17.RecordSupportJDK17OrLaterFeature, []
com.oracle.svm.core.jdk17.SealedClassSupportJDK17OrLaterFeature, []
com.oracle.svm.core.jfr.sampler.JfrNoExecutionSamplerFeature, [com.oracle.svm.core.jfr.JfrFeature]
com.oracle.svm.core.jfr.sampler.JfrRecurringCallbackExecutionSamplerFeature, [com.oracle.svm.core.jfr.JfrFeature]
com.oracle.svm.core.jvmstat.PerfDataFeature, [com.oracle.svm.core.thread.VMOperationListenerSupportFeature com.oracle.svm.core.jdk.RuntimeSupportFeature]
com.oracle.svm.core.meta.SubstrateObjectConstantEqualityFeature, []
com.oracle.svm.core.monitor.MonitorFeature, []
com.oracle.svm.core.option.RuntimeOptionsSupportImplFeature, []
com.oracle.svm.core.option.ValidateImageBuildOptionsFeature, []
com.oracle.svm.core.os.BufferedFileOperationFeature, []
com.oracle.svm.core.os.ImageHeapProviderFeature, []
com.oracle.svm.core.os.OSCommittedMemoryProviderFeature, []
com.oracle.svm.core.posix.IgnoreSIGPIPEFeature, []
com.oracle.svm.core.posix.PosixLoadAverageSupportFeature, []
com.oracle.svm.core.posix.PosixLogHandlerFeature, []
com.oracle.svm.core.posix.PosixNativeLibraryFeature, []
com.oracle.svm.core.posix.PosixRawFileOperationFeature, []
com.oracle.svm.core.posix.PosixSubstrateSegfaultHandlerFeature, []
com.oracle.svm.core.posix.PosixSubstrateSigProfHandlerFeature, [com.oracle.svm.core.IsolateListenerSupportFeature com.oracle.svm.core.jfr.JfrFeature]
com.oracle.svm.core.posix.PosixVirtualMemoryProviderFeature, []
com.oracle.svm.core.posix.UnmanagedMemorySupportImplFeature, []
com.oracle.svm.core.posix.amd64.AMD64LinuxUContextRegisterDumperFeature, []
com.oracle.svm.core.posix.heapdump.AllocationFreeFileOutputStreamPosixFeature, []
com.oracle.svm.core.posix.linux.LinuxImageSingletonsFeature, []
com.oracle.svm.core.posix.linux.LinuxPhysicalMemorySupportImplFeature, []
com.oracle.svm.core.posix.linux.LinuxProcessPropertiesSupportFeature, []
com.oracle.svm.core.posix.linux.LinuxStackOverflowSupportFeature, []
com.oracle.svm.core.posix.linux.LinuxSystemPropertiesFeature, []
com.oracle.svm.core.posix.linux.LinuxThreadCpuTimeSupportFeature, []
com.oracle.svm.core.posix.linux.LinuxVMSemaphoreFeature, []
com.oracle.svm.core.posix.pthread.PthreadVMLockFeature, []
com.oracle.svm.core.posix.thread.PosixParkerFactoryFeature, []
com.oracle.svm.core.posix.thread.PosixPlatformThreadsFeature, []
com.oracle.svm.core.posix.thread.PosixVMThreadsFeature, []
com.oracle.svm.core.reflect.target.ReflectionMetadataDecoderImplFeature, []
com.oracle.svm.core.reflect.target.ReflectionMetadataDecoderImplMetadataAccessorImplFeature, []
com.oracle.svm.core.reflect.target.ReflectionMetadataEncodingFeature, []
com.oracle.svm.core.thread.ContinuationsFeature, []
com.oracle.svm.core.thread.JavaThreadsFeature, []
com.oracle.svm.core.thread.SafepointMasterFeature, []
com.oracle.svm.core.thread.ThreadListenerSupportFeature, []
com.oracle.svm.core.thread.ThreadingSupportImplFeature, []
com.oracle.svm.core.thread.VMOperationControlFeature, []
com.oracle.svm.core.thread.VMOperationListenerSupportFeature, []
com.oracle.svm.core.threadlocal.VMThreadLocalInfosFeature, []
com.oracle.svm.core.util.CounterFeature, []
com.oracle.svm.core.util.HostedStringDeduplicationFeature, []
com.oracle.svm.graal.RuntimeCPUFeatureRegionFeature, []
com.oracle.svm.graal.isolated.DisableSnippetCountersFeature, []
com.oracle.svm.graal.isolated.IsolateAwareObjectConstantEqualityFeature, []
com.oracle.svm.graal.meta.amd64.AMD64RuntimeCodeInstallerPlatformHelperFeature, []
com.oracle.svm.graal.stubs.AMD64StubForeignCallsFeature, []
com.oracle.svm.hosted.AMD64CPUFeatureAccessFeature, []
com.oracle.svm.hosted.ClassLoaderFeature, []
com.oracle.svm.hosted.ClassNewInstanceFeature, []
com.oracle.svm.hosted.ClassPredefinitionFeature, []
com.oracle.svm.hosted.ClassValueFeature, []
com.oracle.svm.hosted.ConcurrentReachabilityHandler, []
com.oracle.svm.hosted.FallbackFeature, []
com.oracle.svm.hosted.Log4ShellFeature, []
com.oracle.svm.hosted.LoggingFeature, []
com.oracle.svm.hosted.ModuleLayerFeature, []
com.oracle.svm.hosted.NativeSecureRandomFilesCloser, []
com.oracle.svm.hosted.ProgressReporterFeature, []
com.oracle.svm.hosted.ProtectionDomainFeature, []
com.oracle.svm.hosted.ResourcesFeature, []
com.oracle.svm.hosted.SecurityServicesFeature, []
com.oracle.svm.hosted.ServiceLoaderFeature, []
com.oracle.svm.hosted.SubstrateDiagnosticFeature, []
com.oracle.svm.hosted.SystemInOutErrFeature, []
com.oracle.svm.hosted.VMFeature, []
com.oracle.svm.hosted.ameta.HostedDynamicHubFeature, []
com.oracle.svm.hosted.annotation.AnnotationSupportFeature, []
com.oracle.svm.hosted.annotation.AnnotationTypeFeature, []
com.oracle.svm.hosted.c.CGlobalDataFeature, []
com.oracle.svm.hosted.c.function.CEntryPointSupport, []
com.oracle.svm.hosted.c.libc.HostedLibCFeature, []
com.oracle.svm.hosted.classinitialization.ClassInitializationFeature, []
com.oracle.svm.hosted.code.CEntryPointCallStubFeature, []
com.oracle.svm.hosted.code.CEntryPointLiteralFeature, []
com.oracle.svm.hosted.code.CFunctionLinkagesFeature, []
com.oracle.svm.hosted.code.CFunctionPointerCallStubSupportFeature, []
com.oracle.svm.hosted.code.FactoryMethodSupportFeature, []
com.oracle.svm.hosted.code.FrameInfoHostedMethodDataFeature, []
com.oracle.svm.hosted.code.RestrictHeapAccessCalleesFeature, []
com.oracle.svm.hosted.code.SubstrateCompilationDirectivesFeature, []
com.oracle.svm.hosted.code.SubstrateLIRBackendFeature, []
com.oracle.svm.hosted.code.UninterruptibleAnnotationCheckerFeature, []
com.oracle.svm.hosted.code.amd64.AMD64HostedPatcherFeature, []
com.oracle.svm.hosted.code.amd64.AMD64HostedTrampolineSupportFeature, []
com.oracle.svm.hosted.fieldfolding.StaticFinalFieldFoldingFeature, []
com.oracle.svm.hosted.heap.HeapDumpFeature, []
com.oracle.svm.hosted.heap.ImageHeapMapFeature, []
com.oracle.svm.hosted.heap.PodFeature, []
com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature, [com.oracle.svm.core.jdk.management.ManagementFeature]
com.oracle.svm.hosted.image.ImageHeapFillerObjectsFeature, []
com.oracle.svm.hosted.image.MethodPointerInvalidHandlerFeature, []
com.oracle.svm.hosted.image.StringInternFeature, []
com.oracle.svm.hosted.image.sources.SourceCacheFeature, []
com.oracle.svm.hosted.jdk.AccessControlContextReplacerFeature, []
com.oracle.svm.hosted.jdk.JDKInitializationFeature, []
com.oracle.svm.hosted.jdk.JDKRegistrations, []
com.oracle.svm.hosted.jdk.JNIRegistrationAWTSupport, []
com.oracle.svm.hosted.jdk.JNIRegistrationJava, []
com.oracle.svm.hosted.jdk.JNIRegistrationJavaNet, []
com.oracle.svm.hosted.jdk.JNIRegistrationJavaNio, []
com.oracle.svm.hosted.jdk.JNIRegistrationManagementExt, []
com.oracle.svm.hosted.jdk.JNIRegistrationPrefs, []
com.oracle.svm.hosted.jdk.JNIRegistrationSupport, []
com.oracle.svm.hosted.jdk.JNIRegistrationsJavaZip, []
com.oracle.svm.hosted.jdk.JRTFeature, []
com.oracle.svm.hosted.jdk.localization.CharsetSubstitutionsFeature, []
com.oracle.svm.hosted.jdk.localization.LocalizationFeature, []
com.oracle.svm.hosted.jdk17.JNIRegistrationSupport_JDK17OrLater, []
com.oracle.svm.hosted.jni.JNIAccessFeature, [com.oracle.svm.hosted.meta.KnownOffsetsFeature]
com.oracle.svm.hosted.jni.JNIAutomaticFeature, [com.oracle.svm.hosted.jni.JNIFeature]
com.oracle.svm.hosted.jni.JNICallWrapperFeature, [com.oracle.svm.hosted.jni.JNIAccessFeature]
com.oracle.svm.hosted.jni.JNIFeature, [com.oracle.svm.hosted.jni.JNIFunctionTablesFeature com.oracle.svm.hosted.jni.JNICallWrapperFeature com.oracle.svm.hosted.jni.JNILibraryLoadFeature]
com.oracle.svm.hosted.jni.JNIFunctionTablesFeature, [com.oracle.svm.hosted.jni.JNIAccessFeature]
com.oracle.svm.hosted.jni.JNILibraryLoadFeature, []
com.oracle.svm.hosted.lambda.StableLambdaProxyNameFeature, []
com.oracle.svm.hosted.meta.HostedMethodNameFactory, []
com.oracle.svm.hosted.meta.InvalidVTableEntryFeature, []
com.oracle.svm.hosted.meta.KnownOffsetsFeature, [com.oracle.svm.hosted.thread.VMThreadMTFeature]
com.oracle.svm.hosted.meta.MaterializedConstantFieldsFeature, []
com.oracle.svm.hosted.methodhandles.MethodHandleFeature, []
com.oracle.svm.hosted.option.RuntimeOptionFeature, []
com.oracle.svm.hosted.phases.EnumSwitchFeature, []
com.oracle.svm.hosted.reflect.ReflectionFeature, []
com.oracle.svm.hosted.reflect.ReflectionMetadataEncoderImplFactoryFeature, []
com.oracle.svm.hosted.reflect.proxy.DynamicProxyFeature, [com.oracle.svm.hosted.reflect.ReflectionFeature]
com.oracle.svm.hosted.reflect.serialize.SerializationFeature, [com.oracle.svm.hosted.reflect.ReflectionFeature com.oracle.svm.hosted.reflect.proxy.DynamicProxyFeature]
com.oracle.svm.hosted.snippets.ExceptionUnwindFeature, []
com.oracle.svm.hosted.snippets.ImplicitExceptionsFeature, []
com.oracle.svm.hosted.substitute.AutomaticSubstitutionFeature, []
com.oracle.svm.hosted.thread.CEntryPointFeature, [com.oracle.svm.hosted.thread.VMThreadMTFeature]
com.oracle.svm.hosted.thread.VMThreadMTFeature, []
com.oracle.svm.hosted.xml.JavaxXmlClassAndResourcesLoaderFeature, []
com.oracle.svm.truffle.TruffleJFRFeature, []
```

</details>

**Comment by Selebrator** [comment]
Updating to https://mvnrepository.com/artifact/org.graalvm.nativeimage/svm/23.1.0 does not fix the issue.
